"""Locale string registry for all generators.

Usage:
    from scripts.generators.strings import t
    heading = t("section_overview", lang)  # lang = "ko" | "en"
"""

from __future__ import annotations


STRINGS: dict[str, dict[str, str]] = {
    "ko": {
        "section_overview": "개요",
        "section_timing": "타이밍 & 감쇠",
        "section_pipeline": "파이프라인",
        "section_formula": "수식",
        "section_formulas": "수식",
        "section_constants": "상수",
        "section_interactions": "상호작용",
        "section_traits": "특성 효과",
        "section_glossary": "용어 사전",
        "section_signals": "시그널",
        "section_references": "레퍼런스",
        "section_data": "데이터",
        "section_config_reference": "설정 레퍼런스",
        "section_project_stats": "프로젝트 통계",
        "section_key_sections": "주요 섹션",
        "section_sim_architecture": "시뮬레이션 아키텍처",
        "section_tick_pipeline": "틱 파이프라인",
        "section_pipeline_diagram": "파이프라인 다이어그램",
        "section_cross_system_effects": "시스템 간 상호작용",
        "section_imported_modules": "모듈 임포트",
        "section_shared_entity_fields": "공유 엔티티 필드",
        "section_downstream_impact": "다운스트림 영향",
        "section_entity_data_model": "엔티티 데이터 모델",
        "section_manual_notes": "수동 노트",
        "section_academic_refs": "참고 문헌",
        "section_specialized_docs": "전용 문서",
        "section_summary": "요약",
        "section_interpreted_parameters": "해석된 파라미터",
        "section_domain_summary": "도메인 요약",
        "section_mortality_model_interpretation": "사망 모델 해석",
        "section_baseline_parameters": "기본 파라미터",
        "section_technology_modifiers": "기술 보정",
        "section_infant_care_protection": "영아 보호",
        "section_seasonal_environment_effects": "계절 환경 영향",
        "section_source_notes": "소스 노트",
        "section_architecture": "아키텍처",
        "section_axis_overview": "축 개요",
        "section_trait_types": "특성 유형",
        "section_how_traits_work": "특성 작동 방식",
        "section_axis_pages": "축 페이지",
        "section_synergy_network": "시너지 네트워크",
        "section_event_to_emotion_pipeline": "이벤트→감정 파이프라인",
        "section_emotional_contagion": "감정 전염",
        "section_mental_break": "정신 붕괴",
        "section_event_presets": "이벤트 프리셋",
        "section_personality_modifiers": "성격 보정",
        "section_stress_pipeline": "스트레스 파이프라인",
        "section_lazarus_appraisal_scale": "Lazarus 평가 스케일",
        "section_continuous_stressors": "지속 스트레스원",
        "section_emotion_stress_contribution": "감정→스트레스 기여",
        "section_stress_recovery": "스트레스 회복",
        "section_allostatic_load": "알로스타틱 부하",
        "section_gas": "일반 적응 증후군",
        "section_yerkes_dodson": "Yerkes-Dodson 효율 곡선",
        "section_stressor_events": "스트레스 이벤트",
        "section_by_category": "카테고리별",
        "section_break_types": "붕괴 유형",
        "section_interaction_overview": "상호작용 개요",
        "section_calculation_flow_diagram": "계산 흐름 다이어그램",
        "section_interaction_pages": "상호작용 페이지",
        "section_system_dependency_graph": "시스템 의존 그래프",
        "section_core_modules": "코어 모듈",
        "section_public_api": "공개 API",
        "section_dependencies": "의존성",
        "section_utility_functions": "유틸리티 함수",
        "section_enums": "열거형",
        "section_dictionaries": "사전",
        "section_feedback_loops": "피드백 루프",
        "section_example_partner_loss": "예시: 동반자 상실",
        "section_pipeline_statistics": "파이프라인 통계",
        "stage1_personality": "1단계: 성격 (정적 기반)",
        "stage2_emotion": "2단계: 감정 (빠른 반응)",
        "stage3_stress": "3단계: 스트레스 (중간 축적)",
        "stage4_mortality": "4단계: 사망 (느린 선택)",
        "subsection_input": "입력",
        "subsection_computation": "계산",
        "subsection_output": "출력",
        "subsection_bereavement_cascade": "애도 연쇄",
        "subsection_mental_break_loop": "정신 붕괴 루프",
        "group_timing_decay": "타이밍 & 감쇠",
        "group_thresholds_bounds": "임계 & 경계",
        "group_weights_multipliers": "가중치 & 배수",
        "group_probabilities": "확률",
        "group_stress_emotion": "스트레스 & 감정",
        "group_identifiers_labels": "식별자 & 라벨",
        "group_other_parameters": "기타 파라미터",
        "domain_species": "종족",
        "domain_emotions": "감정",
        "domain_personality": "성격",
        "domain_stress": "스트레스",
        "domain_unknown": "미상",
        "label_source": "📄 소스:",
        "label_category": "분류",
        "label_type": "유형",
        "label_parameter": "매개변수",
        "label_value": "값",
        "label_metric": "지표",
        "label_controls": "게임 영향",
        "label_generated": "생성일",
        "label_priority": "우선순위",
        "label_tick_interval": "틱 간격",
        "label_core_entity_data": "핵심 엔티티 데이터",
        "label_configures": "설정 내용",
        "label_read_by_modules": "읽는 시스템/모듈",
        "label_related_docs": "관련 문서",
        "label_total_files": "총 파일 수",
        "label_total_entries": "총 항목 수",
        "label_total_categories": "총 카테고리 수",
        "label_items": "항목 수",
        "label_key_count": "키 수",
        "label_files": "파일 수",
        "label_domain": "도메인",
        "label_output_page": "출력 페이지",
        "label_interaction_pair": "상호작용 쌍",
        "status_none": "없음",
        "status_none_found": "찾지 못함",
        "status_not_found": "찾을 수 없음",
        "status_not_inferred_from_references": "references.json에서 추론되지 않음",
        "status_no_data": "데이터 없음",
        "status_missing": "누락",
        "status_unknown": "미상",
        "status_untranslated_ko": "⚠️ 미번역",
        "status_untranslated_en": "⚠️ untranslated",
        "warn_incomplete": "⚠️ EXTRACTION INCOMPLETE",
        "warn_missing_section": "섹션 누락 또는 형식 오류",
        "warn_missing_source": "소스 파일 누락",
        "warn_invalid_payload": "페이로드 형식 오류",
        "phrase_korean_english": "한국어 / English",
        "phrase_reads_shared_fields": "공유 필드 읽기",
        "phrase_writes_shared_fields": "공유 필드 쓰기",
        "phrase_no_interpretable_parameters": "해석 가능한 파라미터 없음",
        "phrase_no_references": "참조 없음",
        "phrase_no_shared_fields": "공유 필드가 추론되지 않음",
        "phrase_no_imports": "임포트 관계가 추출되지 않음",
        "phrase_no_signals": "시그널 메타데이터가 추출되지 않음",
        "phrase_no_downstream": "다운스트림 의존성이 추출되지 않음",
        "phrase_no_config_refs": "GameConfig 참조가 추출되지 않음",
        "phrase_no_tick_pipeline": "틱 파이프라인 메타데이터가 추출되지 않음",
    },
    "en": {
        "section_overview": "Overview",
        "section_timing": "Timing & Decay",
        "section_pipeline": "Pipeline",
        "section_formula": "Formula",
        "section_formulas": "Formulas",
        "section_constants": "Constants",
        "section_interactions": "Interactions",
        "section_traits": "Trait Effects",
        "section_glossary": "Glossary",
        "section_signals": "Signals",
        "section_references": "References",
        "section_data": "Data",
        "section_config_reference": "Config Reference",
        "section_project_stats": "Project Statistics",
        "section_key_sections": "Key Sections",
        "section_sim_architecture": "Simulation Architecture",
        "section_tick_pipeline": "Tick Pipeline",
        "section_pipeline_diagram": "Pipeline Diagram",
        "section_cross_system_effects": "Cross-System Effects",
        "section_imported_modules": "Imported Modules",
        "section_shared_entity_fields": "Shared Entity Fields",
        "section_downstream_impact": "Downstream Impact",
        "section_entity_data_model": "Entity Data Model",
        "section_manual_notes": "Manual Notes",
        "section_academic_refs": "Academic References",
        "section_specialized_docs": "Specialized Documentation",
        "section_summary": "Summary",
        "section_interpreted_parameters": "Interpreted Parameters",
        "section_domain_summary": "Domain Summary",
        "section_mortality_model_interpretation": "Mortality Model Interpretation",
        "section_baseline_parameters": "Baseline Parameters",
        "section_technology_modifiers": "Technology Modifiers",
        "section_infant_care_protection": "Infant Care Protection",
        "section_seasonal_environment_effects": "Seasonal Environment Effects",
        "section_source_notes": "Source Notes",
        "section_architecture": "Architecture",
        "section_axis_overview": "Axis Overview",
        "section_trait_types": "Trait Types",
        "section_how_traits_work": "How Traits Work",
        "section_axis_pages": "Axis Pages",
        "section_synergy_network": "Synergy Network",
        "section_event_to_emotion_pipeline": "Event to Emotion Pipeline",
        "section_emotional_contagion": "Emotional Contagion",
        "section_mental_break": "Mental Break",
        "section_event_presets": "Event Presets",
        "section_personality_modifiers": "Personality Modifiers",
        "section_stress_pipeline": "Stress Pipeline",
        "section_lazarus_appraisal_scale": "Lazarus Appraisal Scale",
        "section_continuous_stressors": "Continuous Stressors",
        "section_emotion_stress_contribution": "Emotion to Stress Contribution",
        "section_stress_recovery": "Stress Recovery",
        "section_allostatic_load": "Allostatic Load",
        "section_gas": "General Adaptation Syndrome",
        "section_yerkes_dodson": "Yerkes-Dodson Efficiency Curve",
        "section_stressor_events": "Stressor Events",
        "section_by_category": "By Category",
        "section_break_types": "Break Types",
        "section_interaction_overview": "Interaction Overview",
        "section_calculation_flow_diagram": "Calculation Flow Diagram",
        "section_interaction_pages": "Interaction Pages",
        "section_system_dependency_graph": "System Dependency Graph",
        "section_core_modules": "Core Modules",
        "section_public_api": "Public API",
        "section_dependencies": "Dependencies",
        "section_utility_functions": "Utility Functions",
        "section_enums": "Enums",
        "section_dictionaries": "Dictionaries",
        "section_feedback_loops": "Feedback Loops",
        "section_example_partner_loss": "Example: Entity Loses Partner",
        "section_pipeline_statistics": "Pipeline Statistics",
        "stage1_personality": "Stage 1: Personality (Static Foundation)",
        "stage2_emotion": "Stage 2: Emotion (Fast Response)",
        "stage3_stress": "Stage 3: Stress (Medium Accumulation)",
        "stage4_mortality": "Stage 4: Mortality (Slow Selection)",
        "subsection_input": "Input",
        "subsection_computation": "Computation",
        "subsection_output": "Output",
        "subsection_bereavement_cascade": "Bereavement Cascade",
        "subsection_mental_break_loop": "Mental Break Loop",
        "group_timing_decay": "Timing & Decay",
        "group_thresholds_bounds": "Thresholds & Bounds",
        "group_weights_multipliers": "Weights & Multipliers",
        "group_probabilities": "Probabilities",
        "group_stress_emotion": "Stress & Emotion",
        "group_identifiers_labels": "Identifiers & Labels",
        "group_other_parameters": "Other Parameters",
        "domain_species": "Species",
        "domain_emotions": "Emotions",
        "domain_personality": "Personality",
        "domain_stress": "Stress",
        "domain_unknown": "Unknown",
        "label_source": "📄 source:",
        "label_category": "Category",
        "label_type": "Type",
        "label_parameter": "Parameter",
        "label_value": "Value",
        "label_metric": "Metric",
        "label_controls": "What it controls",
        "label_generated": "Generated",
        "label_priority": "Priority",
        "label_tick_interval": "Tick interval",
        "label_core_entity_data": "Core entity data",
        "label_configures": "Configures",
        "label_read_by_modules": "Read by systems/modules",
        "label_related_docs": "Related documentation",
        "label_total_files": "Total files",
        "label_total_entries": "Total entries",
        "label_total_categories": "Total categories",
        "label_items": "Items",
        "label_key_count": "Key count",
        "label_files": "Files",
        "label_domain": "Domain",
        "label_output_page": "Output page",
        "label_interaction_pair": "Interaction pair",
        "status_none": "None",
        "status_none_found": "None found",
        "status_not_found": "Not found",
        "status_not_inferred_from_references": "Not inferred from references.json",
        "status_no_data": "No data",
        "status_missing": "Missing",
        "status_unknown": "Unknown",
        "status_untranslated_ko": "⚠️ untranslated",
        "status_untranslated_en": "⚠️ untranslated",
        "warn_incomplete": "⚠️ EXTRACTION INCOMPLETE",
        "warn_missing_section": "Missing or invalid section",
        "warn_missing_source": "Missing source file",
        "warn_invalid_payload": "Invalid payload",
        "phrase_korean_english": "Korean / English",
        "phrase_reads_shared_fields": "Reads shared fields",
        "phrase_writes_shared_fields": "Writes shared fields",
        "phrase_no_interpretable_parameters": "No interpretable parameters found",
        "phrase_no_references": "No references",
        "phrase_no_shared_fields": "No shared fields inferred",
        "phrase_no_imports": "No import relationships extracted",
        "phrase_no_signals": "No signal metadata extracted",
        "phrase_no_downstream": "No downstream dependencies extracted",
        "phrase_no_config_refs": "No GameConfig references extracted",
        "phrase_no_tick_pipeline": "No tick pipeline metadata extracted",
    },
}


def t(key: str, lang: str = "ko") -> str:
    """Translate key to given language, falling back to ko then key itself."""
    return STRINGS.get(lang, STRINGS["ko"]).get(key, STRINGS["ko"].get(key, key))


if set(STRINGS["ko"]) != set(STRINGS["en"]):
    missing_in_en = sorted(set(STRINGS["ko"]) - set(STRINGS["en"]))
    missing_in_ko = sorted(set(STRINGS["en"]) - set(STRINGS["ko"]))
    raise ValueError(
        "Locale registry key mismatch. "
        f"missing_in_en={missing_in_en}, missing_in_ko={missing_in_ko}"
    )
